version: '3.3'

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  postgis-data:
  postgis-backups:
  geoserver-data:
  shiny-apps:

services:

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    env_file: .env
    environment:
      DEFAULT_HOST: www.$HOST
      VIRTUAL_HOST_SPECIFIC_PORT: 'true'
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-proxy/nginx.tmpl:/app/nginx.tmpl:ro"
      - "nginx-certs:/etc/nginx/certs:ro"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt
    environment:
      DEFAULT_EMAIL: 'ben@ecoquants.com'
      NGINX_PROXY_CONTAINER: proxy
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "nginx-certs:/etc/nginx/certs:rw"
     - "nginx-vhost:/etc/nginx/vhost.d"
     - "nginx-html:/usr/share/nginx/html"
    depends_on: 
     - proxy
     
  postgis:
    container_name: postgis
    image: kartoza/postgis:11.0-2.5
    environment:
      PGGSSENCMODE: disable # https://github.com/petere/homebrew-postgresql/issues/51
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $PASSWORD
    volumes:
      - postgis-data:/var/lib/postgresql
      - /share:/share
    restart: unless-stopped
    healthcheck:
      test: 'exit 0'
    ports:
      - 5432:5432

  postgis-backup:
    container_name: postgis-backup
    image: kartoza/pg-backup:11.0
    volumes:
      - postgis-backups:/backups
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASS: $PASSWORD
      DUMPPREFIX: PG_gis
    restart: unless-stopped
    depends_on:
      - postgis

  geoserver:
    container_name: geoserver
    image: kartoza/geoserver:2.15.2
    environment:
      VIRTUAL_HOST: gs.$HOST
      LETSENCRYPT_HOST: "gs.$HOST"
      USERNAME: admin
      PASS: $PASSWORD
      GEOSERVER_ADMIN_PASSWORD: $PASSWORD
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - /share:/share      
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgis
    healthcheck:
      test: curl --fail -s http://localhost:8888/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  rstudio:
    container_name: rstudio
    build: ./rstudio-shiny
    image: bdbest/rstudio-shiny:mhk-env
    volumes:
      - /share:/share    
      - shiny-apps:/srv/shiny-server
    restart: unless-stopped
    environment:
      # [Running virtual hosts on different ports of the same container · Issue #560 · jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy/issues/560)
      VIRTUAL_HOST: "rstudio.$HOST:8787,shiny.$HOST:3838"
      LETSENCRYPT_HOST: "rstudio.$HOST,shiny.$HOST,api.$HOST"
      ROOT: 'true'
      USER: admin
      PASSWORD: $PASSWORD
    ports:
      - 8787:8787 # rstudio
      - 3838:3838 # shiny
      - 8888:8888 # api      

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - /share:/share    
      - nginx-html:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: www.$HOST
    ports:
      - 8088:80

  